Lesson 8: Add products and attributes web
anslava00/fefu_backend_3_6 pull request #11
Opened 2022-05-20 04:02 UTC by anslava00

2022-05-21 11:20 UTC, anslava00 commented
![изображение_2022-05-21_211940427](https://user-images.githubusercontent.com/54322057/169649370-4a742a31-d655-48b9-b908-a76f1f19f5df.png)
![изображение_2022-05-21_211959024](https://user-images.githubusercontent.com/54322057/169649376-1987c080-8c63-4887-91be-be41af87491d.png)

2022-05-21 11:21 UTC, anslava00 commented
столкнулся с проблемой не получается решить
причем вроде все работало на следующий день вот чет запустил докер доделывать api и ошибку ловлю

2022-05-22 05:50 UTC, chrn-feip requested changes

2022-05-22 05:50 UTC, chrn-feip commented on app/Enums/AbstractEnum.php
> +class AbstractEnum
abstract class

2022-05-22 05:50 UTC, chrn-feip commented on app/Enums/ProductAttributeType.php
> +class ProductAttributeType extends AbstractEnum
final class

2022-05-22 05:50 UTC, chrn-feip commented on app/Models/ProductCategory.php
> +        return Product::query()->whereId('product_category_id', $categoryIds);
whereIn вместо whereId. Ваше условие применяется именно к id, поэтому в SQL в ошибке вы видите where id = product_category_id.

2022-05-22 05:50 UTC, chrn-feip commented on app/Models/ProductCategory.php
> +    {
Сделайте тут ещё проверку, что коллекция $categories не пустая, иначе запрос whereIn упадёт для пустого массива параметров. Если коллекция пуста, то `throw new Exception(<Текст ошибки о том, что категории не переданы>)`. А в контроллерах, где вызывается `getTreeProductsBuilder`, делайте вызов внутри try-catch и в  catch ветке делайте `abort(422, $exception->getMessage())`.

2022-05-22 05:50 UTC, chrn-feip commented on database/factories/ProductAttributeValueFactory.php
> +    public function __construct($count = null, ?Collection $states = null, ?Collection $has = null, ?Collection $for = null, ?Collection $afterMaking = null, ?Collection $afterCreating = null, ?Colle
Конструктор и доп. свойства в классе фабрики уже не нужны, вы же перенесли это всё в сидер  и внутри фабрики уже не используете.

2022-05-23 03:20 UTC, chrn-feip requested changes

2022-05-23 03:20 UTC, chrn-feip commented on app/Http/Controllers/Api/ProductApiController.php
> +    #[OpenApi\Operation(tags: ["catalog"])]
А где описание параметров?

2022-05-23 03:20 UTC, chrn-feip commented on app/Http/Controllers/Api/ProductApiController.php
> +    #[OpenApi\Operation(tags: ["catalog"])]
И тут не хватает параметров

2022-05-23 03:20 UTC, chrn-feip commented on app/Http/Controllers/Api/ProductApiController.php
> +                'errors' => $exception->getMessage(),
[$exception->getMessage()], в errors предполагается массив ошибок

2022-05-23 03:20 UTC, chrn-feip commented on app/Models/ProductCategory.php
> +        if ($categories === null){
Не null, тип аргумента же Collection. $categories->isEmpty()

2022-05-23 03:20 UTC, chrn-feip commented on app/Http/Resources/AtributeValuesResources.php
> +class AtributeValuesResources extends JsonResource
Не хватает mixin аннотации

2022-05-23 03:20 UTC, chrn-feip commented on app/Http/Resources/ListCatalogResources.php
> +class ListCatalogResources extends JsonResource
Не хватает mixin аннотации

2022-05-23 03:20 UTC, chrn-feip commented on app/Http/Resources/ProductResources.php
> +class ProductResources extends JsonResource
Не хватает mixin аннотации

2022-05-23 03:20 UTC, chrn-feip commented on app/OpenApi/Schemas/ProductAttributeValueSchema.php
> +class ProductAttributeValueSchema extends SchemaFactory implements Reusable
А зачем эта схема, если она не используется?

2022-05-23 03:20 UTC, chrn-feip commented on app/OpenApi/Responses/CatalogListResponse.php
> +class CatalogListResponse extends ResponseFactory
ProductsListResponse.

2022-05-23 03:20 UTC, chrn-feip commented on app/OpenApi/Responses/CatalogListResponse.php
> +                    ObjectsSchema::array('data')->items(CatalogSchema::ref()),
Что это за схема? У вас же список товаров с сокращённой схемой (аналогично сокращённому ресурсу товара)

2022-05-23 06:57 UTC, anslava00 commented on app/OpenApi/Responses/CatalogListResponse.php
> +                    ObjectsSchema::array('data')->items(CatalogSchema::ref()),
не совсем понял 
получается по пути .../product/list выводится тоже самое что и по .../product/details но без характеристики ? 
я возвращал как в веб части было те (цена имя и родителя всех продуктов по приходящему слагу)

2022-05-23 07:05 UTC, chrn-feip commented on app/OpenApi/Responses/CatalogListResponse.php
> +                    ObjectsSchema::array('data')->items(CatalogSchema::ref()),
В ../product/list возвращается список товаров с пагинацией, об этом же говорит сам url, выбранный для контроллера и метода в нём. В этом списке каждый товар представлен минимумом атрибутов - имя, слаг, цена. Почему же тогда используется схема CatalogSchemа? Нужно сделать два класса схем под товар - ListProductSchema и DetailedProductSchema.

CatalogSchema - это схема для категории товаров, кстати, с неудачным названием. Каталог же у нас один, состоит из множества категорий с товарами. Лучше было бы назвать ProductCategorySchema, так же понятнее.

2022-05-23 07:11 UTC, anslava00 commented on app/OpenApi/Responses/CatalogListResponse.php
> +                    ObjectsSchema::array('data')->items(CatalogSchema::ref()),
понял

2022-05-23 07:30 UTC, anslava00 commented
Не совсем понимаю зачем нужен mixin
как я понял мы комментируем чем является $this ?

2022-05-23 07:36 UTC, chrn-feip commented
> Не совсем понимаю зачем нужен mixin как я понял мы комментируем чем является $this ?

Это аннотация к классу, чтобы работало автодополнение кода, когда вы пишите $this->attr...

2022-05-23 07:43 UTC, chrn-feip requested changes

2022-05-23 07:43 UTC, chrn-feip commented on api-docs.json
> +                        "name": "category_slug",
А здесь же слаг товара, а не категории уже

2022-05-23 07:43 UTC, chrn-feip commented on app/Http/Controllers/Api/ProductApiController.php
>          $slug = $request->query('category_slug');
слаг товара

2022-05-23 07:43 UTC, chrn-feip commented on app/Http/Controllers/Api/ProductApiController.php
> +    #[OpenApi\Parameters(factory: ProductParameters::class)]
разные параметры будут в index и show. И там, и там слаг, но он из разных сущностей и с разным требованием обязательности

2022-05-23 07:43 UTC, chrn-feip commented on app/Http/Resources/ListCatalogResources.php
>  class ListCatalogResources extends JsonResource
Опять с названиями беда. ListProductResource. Единственное число, товар. Вы хоть сопоставляйте контроллеры, бизнес-логику и используемые именования.

2022-05-23 07:43 UTC, chrn-feip commented on app/Http/Resources/ProductResources.php
>  class ProductResources extends JsonResource
DetailedProductResource. Единственное число, тоже товар, но уже не для списка, а для запроса отдельного товара

2022-05-23 07:43 UTC, chrn-feip commented on app/OpenApi/Parameters/ProductParameters.php
> +class ProductParameters extends ParametersFactory {
1. ProductsListParameters
2. Ещё один класс нужен - ProductDetailsParameters, но с product_slug, которые обязателен

2022-05-23 07:43 UTC, chrn-feip commented on app/OpenApi/Responses/ProductsListResponse.php
> +                    ObjectsSchema::array('data')->items(ListProductSchema ::ref()),
тут лишний пробел

2022-05-23 07:43 UTC, chrn-feip commented on app/OpenApi/Schemas/ListProductSchema.php
> +        return Schema::object('ProductCategory')
Почему ProductCategory? Это товар, а не категория, Product

2022-05-23 11:17 UTC, chrn-feip requested changes

2022-05-23 11:17 UTC, chrn-feip commented on app/OpenApi/Parameters/ProductDetailsParameters.php
> +                ->required(false)
И почему оно false, когда я дважды акцентировала внимание, что обязательный параметр?

2022-05-23 11:17 UTC, chrn-feip commented on app/OpenApi/Schemas/DetailedProductSchema.php
> +        return Schema::object('ProductAtributeValue')
Почему??? Верните как было и перегенерируйте документацию.

2022-05-23 11:25 UTC, merged