Lesson2
anslava00/fefu_backend_3_6 pull request #4
Opened 2022-03-29 12:37 UTC by anslava00

2022-03-30 13:05 UTC, chrn-feip requested changes
Здесь всё хорошо, кроме того, что в ветке лишние коммиты и изменения из них. Обновите локальную ветку master, переключитесь на ветку с кодом ДЗ, сделайте git rebase master. В процессе решите конфликты, если будут. Проверьте по git log, что коммиты с ДЗ есть и они наверху в истории. Сделайте git push -f origin ветка. В итоге в PR должны остаться коммиты только по ДЗ.

2022-03-31 06:22 UTC, anslava00 commented
Переделал сейчас правильно ?

2022-03-31 07:54 UTC, chrn-feip commented
> Переделал, сейчас правильно ?

Неправильно. Посмотрите в Files changed. Вы там увидите файлы, которые не имеют отношения к ДЗ.

2022-03-31 12:37 UTC, anslava00 commented
Вроде переделал.

2022-03-31 14:14 UTC, merged