Lesson3
anslava00/fefu_backend_3_6 pull request #5
Opened 2022-04-03 02:44 UTC by anslava00

2022-04-03 04:40 UTC, anslava00 commented
Не совсем понимаю как решать эти конфликты, rebase я сделал .

2022-04-03 05:08 UTC, chrn-feip commented
> Не совсем понимаю как решать эти конфликты, rebase я сделал .

Эти конфликты в процессе rebase, скорее всего, и произошли. Вам нужно их вручную решить, тут - на гитхабе - или локально (после чего сделать git push -f ... ветки)

2022-04-03 16:21 UTC, tonighty requested changes

2022-04-03 16:21 UTC, tonighty commented on app/Http/Controllers/NewsWebController.php
> +        $news_list = News::query()->published()->paginate(5);
Для названий переменных в пхп используется camelCase

2022-04-03 16:21 UTC, tonighty commented on app/Http/Controllers/NewsWebController.php
> +        ->where('slug', '=', $slug)
еще нужно использовать `published()`

2022-04-03 16:21 UTC, tonighty commented on app/Http/Controllers/PageWebController.php
> +        $page_list = Page::query()->paginate(5);
Для названий переменных в пхп используется camelCase. №2

2022-04-03 16:21 UTC, tonighty commented on app/Http/Requests/StoreNewsRequest.php
> +class StoreNewsRequest extends FormRequest
этот файл не нужен.

2022-04-03 16:21 UTC, tonighty commented on app/Http/Requests/UpdateNewsRequest.php
> +class UpdateNewsRequest extends FormRequest
этот файл не нужен. №2

2022-04-03 16:21 UTC, tonighty commented on app/Policies/NewsPolicy.php
> +class NewsPolicy
этот файл не нужен. №3

2022-04-03 16:21 UTC, tonighty commented on resources/views/vendor/pagination/bootstrap-4.blade.php
> +@if ($paginator->hasPages())
а все эти файлы из `vendor/pagination` хоть как-то используются?

2022-04-04 00:02 UTC, anslava00 commented on app/Providers/AppServiceProvider.php
> +        Paginator::defaultView('vendor.pagination.simple-tailwind');
Здесь меняю стиль пагинатора по умолчанию

2022-04-04 00:05 UTC, anslava00 commented on resources/views/vendor/pagination/bootstrap-4.blade.php
> +@if ($paginator->hasPages())
я использую simple-tailwind для того чтобы стрелки по умолчанию не выводились огромными, остальные не используются

2022-04-04 03:36 UTC, tonighty requested changes

2022-04-04 03:36 UTC, tonighty commented on app/Http/Controllers/NewsWebController.php
> +        $NewsList = News::query()->published()->paginate(5);
с маленькой буквы все таки $newsList

2022-04-04 05:41 UTC, anslava00 commented
Поменял

2022-04-04 06:46 UTC, anslava00 commented
Поменял но тут я с другой проблемой столкнулся 
не могу зайти на сайт даже на welcome 
бд работает подключение из pgadmin есть 
утром норм все было щас сидел правил и увидел что не могу подключиться 
создал новый проект ларавелевский норм все было 
![изображение_2022-04-04_164232](https://user-images.githubusercontent.com/54322057/161487540-d27d8bee-8c8e-4541-9c40-886c4b24d7a4.png)
![изображение_2022-04-04_164149](https://user-images.githubusercontent.com/54322057/161487442-0b47772c-f989-4e20-9f60-ab956fb7dbb5.png)

2022-04-04 19:59 UTC, tonighty approved these changes

2022-04-04 19:59 UTC, merged