Lesson4
anslava00/fefu_backend_3_6 pull request #6
Opened 2022-04-07 15:04 UTC by anslava00

2022-04-12 00:03 UTC, chrn-feip requested changes

2022-04-12 00:03 UTC, chrn-feip commented on api-docs.json
> +                "summary": "Display the specified resource.",
Это описание того, что делает данный endpoint. Он точно ничего не показывает, поэтому описание некорректно.

2022-04-12 00:03 UTC, chrn-feip commented on api-docs.json
> +            "Appeal": {
Этот объект же не используется

2022-04-12 00:03 UTC, chrn-feip commented on app/Http/Controllers/Api/AppealApiController.php
> +        $appeal->phone = PhoneSanitizer::sanitize($data['phone']);
Тут и для почты нужно ещё дописать $data[...] ?? null. Потому что телефон и почта не являются обязательными и их могут просто не передать в API запросе, т.е. и в массив $data не попадут. А если их там не будет, то попытка обратиться по ключу в массиве приведёт к ошибке.

2022-04-12 00:03 UTC, chrn-feip commented on app/Http/Requests/AppealFormRequest.php
> +    protected function failedValidation(Validator $validator)
Некорректно использовать этот метод в классе, который работает и в веб, и в API контроллере. Вы сейчас не сможете получить правильное поведение в веб-форме, потому что там прежде выполнялся редирект с собранными ошибками, а не исключение с json.
![image](https://user-images.githubusercontent.com/40585429/162851870-d22b9d5b-7ecc-4eaf-9972-5167c0ab0a66.png)

Пока такой вариант можно использовать только в классе-наследнике. Т.о. для веба будет один класс запроса формы, а для апи другой (с этим методом)

2022-04-12 07:08 UTC, anslava00 commented
Поменял

2022-04-13 09:28 UTC, chrn-feip requested changes

2022-04-13 09:28 UTC, chrn-feip commented on api-docs.json
> +                "summary": "Accepts post requests and writes to the DB .",
Я бы сказала, что это "Create new appeal" или "Save appeal submitted data" и т.п.

2022-04-13 10:26 UTC, merged