Lesson5
anslava00/fefu_backend_3_6 pull request #7
Opened 2022-04-16 01:55 UTC by anslava00

Не совсем уверен что правильно написал авторизацию через api
и не понял как в документации в параметрах указывать что надо передавать токен

2022-04-21 08:29 UTC, tonighty requested changes

2022-04-21 08:29 UTC, tonighty commented on app/Http/Controllers/Api/AuthApiController.php
> +        $user = User::where('email', $data['email'])->firstOrFail();
если `Auth::attempt` проходит то юзера можно достать из `Auth::user()`

2022-04-21 08:29 UTC, tonighty commented on app/Http/Controllers/Api/AuthApiController.php
> +        Auth::user()->tokens->each(function($token, $key) {
незачем удалять все токены. достаточно удалить `currentAccessToken`

2022-04-21 08:29 UTC, tonighty commented on app/Http/Kernel.php
> +            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
зачем тебе это понадобилось? запросы с состоянием только в браузере. например, у мобильного приложения нет запросов с сохранением состояния (cookie отсутствуют)

2022-04-21 08:29 UTC, tonighty commented on app/Http/Controllers/Api/AuthApiController.php
> +        $user->name = $data['name'];
не хош в `createFromRequest` унести как в `Appeal` сделано?

2022-04-21 11:33 UTC, anslava00 commented on app/Http/Kernel.php
> +            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
в документации просто указано раскоментить строки эти

2022-04-21 13:11 UTC, tonighty commented on app/Http/Kernel.php
> +            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
это опять же только для браузерных запросов.

2022-04-22 08:20 UTC, anslava00 commented
закоментил строки

2022-04-22 08:26 UTC, merged