Lesson6
anslava00/fefu_backend_3_6 pull request #8
Opened 2022-04-24 01:26 UTC by anslava00

2022-05-02 09:07 UTC, chrn-feip requested changes
Где реализация пункта 2.10 домашнего задания?

2022-05-02 09:07 UTC, chrn-feip commented on resources/views/profile.blade.php
> +            <h3>OAuth info:</h3>
Не нужно дублировать этот заголовок, он должен быть один. Далее список блоков соц. сетей с подзаголовком с названием сети и датами.

2022-05-05 03:33 UTC, chrn-feip requested changes

2022-05-05 03:33 UTC, chrn-feip commented on app/Http/Controllers/Api/AuthApiController.php
> +            $user->save();
А какой в этом смысл, если вы ничего в пользователе не меняете? В БД пользователь, который ранее входил через соц. сеть. А теперь решил зарегистрироваться напрямую, указав почту, имя и пароль. Вот как минимум пароль и даты логина и регистрации ему надо записать.

2022-05-05 03:33 UTC, chrn-feip commented on app/Http/Controllers/Web/AuthController.php
> +            $user->save();
То же самое

2022-05-05 04:03 UTC, anslava00 commented
сейчас правильно ? 
просто не совсем понял задачу сначала

2022-05-05 04:05 UTC, merged